CREATE TABLE `branch_action_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`targetMonth` varchar(7) NOT NULL,
	`monthlyContractTarget` int NOT NULL DEFAULT 0,
	`monthlyPremiumTarget` int NOT NULL DEFAULT 0,
	`monthlyConsultationTarget` int NOT NULL DEFAULT 0,
	`monthlyCallTarget` int NOT NULL DEFAULT 0,
	`monthlyMessageTarget` int NOT NULL DEFAULT 0,
	`monthlyFollowUpTarget` int NOT NULL DEFAULT 0,
	`focusCustomerGroup` text,
	`monthlyStrategy` text,
	`preparationMemo` text,
	`expectedRisk` text,
	`supportRequest` text,
	`managerComment` text,
	`status` enum('draft','submitted','reviewed','revision_requested','closed') NOT NULL DEFAULT 'draft',
	`submittedAt` timestamp,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `branch_action_plans_id` PRIMARY KEY(`id`),
	CONSTRAINT `uq_branch_action_plan_user_month` UNIQUE(`userId`,`targetMonth`)
);
--> statement-breakpoint
CREATE TABLE `weekly_action_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`monthlyPlanId` int NOT NULL,
	`userId` int NOT NULL,
	`weekStartDate` date NOT NULL,
	`weekEndDate` date NOT NULL,
	`weekLabel` varchar(50) NOT NULL,
	`weeklyContractTarget` int NOT NULL DEFAULT 0,
	`weeklyPremiumTarget` int NOT NULL DEFAULT 0,
	`weeklyConsultationTarget` int NOT NULL DEFAULT 0,
	`weeklyCallTarget` int NOT NULL DEFAULT 0,
	`weeklyMessageTarget` int NOT NULL DEFAULT 0,
	`weeklyVisitTarget` int NOT NULL DEFAULT 0,
	`weeklyProposalTarget` int NOT NULL DEFAULT 0,
	`weeklyFollowUpTarget` int NOT NULL DEFAULT 0,
	`focusCustomerGroup` text,
	`weeklyActionPlan` text,
	`preparationMemo` text,
	`expectedRisk` text,
	`supportRequest` text,
	`managerComment` text,
	`status` enum('draft','submitted','reviewed','revision_requested','closed') NOT NULL DEFAULT 'draft',
	`submittedAt` timestamp,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `weekly_action_plans_id` PRIMARY KEY(`id`),
	CONSTRAINT `uq_weekly_action_plan_month_week` UNIQUE(`monthlyPlanId`,`weekStartDate`)
);
--> statement-breakpoint
CREATE TABLE `daily_action_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`weeklyPlanId` int NOT NULL,
	`userId` int NOT NULL,
	`planDate` date NOT NULL,
	`callTarget` int NOT NULL DEFAULT 0,
	`messageTarget` int NOT NULL DEFAULT 0,
	`consultationTarget` int NOT NULL DEFAULT 0,
	`visitTarget` int NOT NULL DEFAULT 0,
	`proposalTarget` int NOT NULL DEFAULT 0,
	`followUpTarget` int NOT NULL DEFAULT 0,
	`todayPriority` text,
	`preparationMemo` text,
	`actualCallCount` int NOT NULL DEFAULT 0,
	`actualMessageCount` int NOT NULL DEFAULT 0,
	`actualConsultationCount` int NOT NULL DEFAULT 0,
	`actualVisitCount` int NOT NULL DEFAULT 0,
	`actualProposalCount` int NOT NULL DEFAULT 0,
	`actualFollowUpCount` int NOT NULL DEFAULT 0,
	`actualResultMemo` text,
	`nextDayMemo` text,
	`managerComment` text,
	`status` enum('draft','submitted','reviewed','revision_requested','closed') NOT NULL DEFAULT 'draft',
	`submittedAt` timestamp,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `daily_action_plans_id` PRIMARY KEY(`id`),
	CONSTRAINT `uq_daily_action_plan_week_date` UNIQUE(`weeklyPlanId`,`planDate`)
);
--> statement-breakpoint
CREATE TABLE `executive_action_plan_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reportMonth` varchar(7) NOT NULL,
	`reportWeekLabel` varchar(50) NOT NULL,
	`generatedBy` int NOT NULL,
	`reportTitle` varchar(200) NOT NULL,
	`branchSummary` text,
	`branchStrategy` text,
	`keyRisks` text,
	`supportRequest` text,
	`executiveMessage` text,
	`downloadReason` text NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `executive_action_plan_reports_id` PRIMARY KEY(`id`)
);
