CREATE TABLE `customer_referrals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`relationshipId` int NOT NULL,
	`referrerCustomerId` int NOT NULL,
	`referredCustomerId` int NOT NULL,
	`referralStage` enum('introduced','contact_ready','contacted','consultation_scheduled','consultation_completed','proposal_made','contracted','deferred','declined','closed') NOT NULL DEFAULT 'introduced',
	`referralSourceType` enum('customer_referral','family_referral','coworker_referral','corporate_referral','friend_referral','other') NOT NULL,
	`introductionMethod` enum('phone','kakao','sms','in_person','group_chat','other'),
	`thankYouStatus` enum('not_required','pending','completed') NOT NULL DEFAULT 'pending',
	`thankYouCompletedAt` timestamp,
	`firstContactedAt` timestamp,
	`consultationStartedAt` timestamp,
	`proposalMadeAt` timestamp,
	`contractedAt` timestamp,
	`declinedAt` timestamp,
	`deferredUntil` timestamp,
	`resultStatus` enum('in_progress','contracted','deferred','declined','closed') NOT NULL DEFAULT 'in_progress',
	`memo` varchar(500),
	`createdBy` int NOT NULL,
	`updatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	CONSTRAINT `customer_referrals_id` PRIMARY KEY(`id`),
	CONSTRAINT `uq_customer_referral_relationship` UNIQUE(`relationshipId`),
	CONSTRAINT `uq_customer_referral_pair` UNIQUE(`referrerCustomerId`,`referredCustomerId`)
);
