import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import ts from "typescript";
import { build } from "esbuild";
import {
  prepareReleaseIdentity,
  readPreStampedReleaseIdentity,
} from "./prepare-release-identity.mjs";
import { verifyReleaseIdentity } from "./stamp-release-identity.mjs";

const A = "13579bdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
const B = "13579bdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
const value = sha => `export const RELEASE_SHA = "${sha}";\n`;
const ambient = sha => `export declare const RELEASE_SHA = "${sha}";\n`;
const DEVELOPMENT = value("development");
const RAILWAY = { RAILWAY_SERVICE_ID: "ambient-test-environment-sentinel" };
const canonical =
  "// Generated by scripts/stamp-release-identity.mjs. Do not edit during deployment.\n" +
  `export const RELEASE_SHA: string = "${A}";\n`;
const hash = bytes => createHash("sha256").update(bytes).digest("hex");

async function fixture(t, source, fileName = "releaseIdentity.ts") {
  const prefix = join(tmpdir(), "boa-ri01-r01-");
  const dir = await mkdtemp(prefix);
  t.after(async () => {
    assert.ok(dir.startsWith(prefix));
    await rm(dir, { recursive: true, force: true });
  });
  const outputPath = join(dir, fileName);
  await writeFile(outputPath, source);
  return outputPath;
}

// Expectations are literal fixture definitions independent of the product reader.
const cases = [
  [
    "C01 typed export declare",
    [`export declare const RELEASE_SHA: string = "${A}";`],
    "invalid",
  ],
  ["C02 untyped export declare", [ambient(A)], "invalid"],
  [
    "C03 uninitialized export declare",
    ["export declare const RELEASE_SHA: string;"],
    "invalid",
  ],
  [
    "C04 ambient value plus export list",
    [`declare const RELEASE_SHA = "${A}"; export { RELEASE_SHA };`],
    "missing",
  ],
  [
    "C05 declaration file",
    ["export const RELEASE_SHA: string;", value(A)],
    "invalid",
    "releaseIdentity.d.ts",
  ],
  [
    "C06 ambient module",
    [`declare module "example" { export const RELEASE_SHA: string; }`],
    "missing",
  ],
  ["C07 nested namespace", [`namespace example { ${value(A)} }`], "missing"],
  ["C08 runtime value", [value(A)], "valid"],
  [
    "C09 runtime plus block example",
    [`/*\n${ambient(B)}*/\n${value(A)}`],
    "valid",
  ],
  ["C10 runtime plus line example", [`// ${ambient(B)}${value(A)}`], "valid"],
  [
    "C11 CRLF formatting",
    [`// keep formatting\r\n export const RELEASE_SHA : string = '${A}' ;\r\n`],
    "valid",
  ],
  ["C12 development plus ambient", [DEVELOPMENT + ambient(A)], "ambiguous"],
  [
    "C13 development plus ambient and comment",
    [`/*\n${value(B)}*/\n${DEVELOPMENT}${ambient(A)}`],
    "ambiguous",
  ],
  ["C14 native env overrides ambient", [ambient(B)], "native"],
  [
    "C15 native env overrides malformed ambient",
    [
      `export declare const RELEASE_SHA = "unterminated`,
      ambient(B) + "/* unterminated",
    ],
    "native",
  ],
  ["C16 two runtime declarations", [value(A) + value(B)], "ambiguous"],
  ["C17 runtime plus ambient duplicate", [value(A) + ambient(B)], "ambiguous"],
  ["C18 ambient plus development", [ambient(A) + DEVELOPMENT], "ambiguous"],
  [
    "C19 as const is not a literal initializer",
    [`export const RELEASE_SHA = "${A}" as const;`],
    "invalid",
  ],
  [
    "C20 dynamic initializers",
    [
      `export const RELEASE_SHA = ("${A}");`,
      `export const RELEASE_SHA = "${A}" + "";`,
      `export const RELEASE_SHA = String("${A}");`,
    ],
    "invalid",
  ],
];

for (const [name, sources, expected, fileName] of cases) {
  test(name, async t => {
    for (const source of sources) {
      const outputPath = await fixture(t, source, fileName);
      const before = await readFile(outputPath);
      if (expected !== "native") {
        assert.deepEqual(
          readPreStampedReleaseIdentity(source, outputPath),
          expected === "valid"
            ? { status: "valid", releaseSha: A }
            : { status: expected }
        );
      }
      if (expected === "native") {
        assert.deepEqual(
          await prepareReleaseIdentity({
            outputPath,
            env: { ...RAILWAY, RAILWAY_GIT_COMMIT_SHA: A },
          }),
          { source: "railway-git" }
        );
        assert.equal(await readFile(outputPath, "utf8"), canonical);
        await verifyReleaseIdentity({ outputPath, releaseSha: A });
      } else {
        if (expected === "valid") {
          assert.deepEqual(
            await prepareReleaseIdentity({ outputPath, env: RAILWAY }),
            { source: "pre-stamped" }
          );
        } else {
          await assert.rejects(
            prepareReleaseIdentity({ outputPath, env: RAILWAY }),
            {
              code:
                expected === "ambiguous"
                  ? "RAILWAY_RELEASE_IDENTITY_AMBIGUOUS"
                  : "RAILWAY_RELEASE_IDENTITY_MISSING",
            }
          );
          assert.deepEqual(
            await prepareReleaseIdentity({ outputPath, env: {} }),
            { source: "development-noop" }
          );
        }
        const after = await readFile(outputPath);
        assert.deepEqual(after, before);
        assert.equal(hash(after), hash(before));
      }
    }
  });
}

function emittedRuntimeExports(source) {
  // Independent evidence: actually run TypeScript emit, not the product reader.
  const emitted = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.ESNext,
      target: ts.ScriptTarget.ES2022,
    },
  }).outputText;
  const tree = ts.createSourceFile(
    "emitted.js",
    emitted,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.JS
  );
  return tree.statements
    .filter(ts.isVariableStatement)
    .filter(statement =>
      statement.modifiers?.some(m => m.kind === ts.SyntaxKind.ExportKeyword)
    )
    .flatMap(statement =>
      statement.declarationList.declarations.map(d => d.name.getText(tree))
    );
}

test("E01 normal runtime export exists in emitted JavaScript", () => {
  assert.deepEqual(emittedRuntimeExports(value(A)), ["RELEASE_SHA"]);
});

test("E02 export declare has no emitted runtime identity", () => {
  for (const source of [
    ambient(A),
    `export declare const RELEASE_SHA: string = "${A}";`,
  ]) {
    assert.deepEqual(emittedRuntimeExports(source), []);
  }
});

test("E03 ambient module has no emitted runtime identity", () => {
  assert.deepEqual(
    emittedRuntimeExports(`declare module "example" { ${value(A)} }`),
    []
  );
});

async function bundleMetadata(outputPath) {
  return build({
    entryPoints: [
      fileURLToPath(new URL("../server/_core/appVersion.ts", import.meta.url)),
    ],
    bundle: true,
    platform: "node",
    format: "esm",
    write: false,
    logLevel: "silent",
    plugins: [
      {
        name: "synthetic-release-source",
        setup(builder) {
          builder.onResolve({ filter: /generated\/releaseIdentity$/ }, () => ({
            path: outputPath,
          }));
        },
      },
    ],
  });
}

test("E04 preserved runtime source satisfies the actual server metadata import", async t => {
  const source = `/* retained example */\r\n${value(A).replaceAll("\n", "\r\n")}`;
  const outputPath = await fixture(t, source);
  const before = await readFile(outputPath);
  assert.deepEqual(await prepareReleaseIdentity({ outputPath, env: RAILWAY }), {
    source: "pre-stamped",
  });
  const result = await bundleMetadata(outputPath);
  assert.equal(result.errors.length, 0);
  assert.ok(result.outputFiles[0].text.includes(A));
  assert.equal(hash(await readFile(outputPath)), hash(before));
});

test("E05 ambient-only CLI rejects before the bundler is attempted", async t => {
  for (const [source, fileName] of [
    [ambient(A), "releaseIdentity.ts"],
    [value(A), "releaseIdentity.d.ts"],
  ]) {
    const outputPath = await fixture(
      t,
      "// ambient-source-sentinel\n" + source,
      fileName
    );
    const before = await readFile(outputPath);
    const cli = spawnSync(
      process.execPath,
      [
        fileURLToPath(
          new URL("./prepare-release-identity.mjs", import.meta.url)
        ),
        "--output",
        outputPath,
      ],
      {
        env: RAILWAY,
        encoding: "utf8",
        windowsHide: true,
      }
    );
    assert.equal(cli.status, 1);
    assert.equal(cli.stdout, "");
    assert.deepEqual(JSON.parse(cli.stderr), {
      ok: false,
      code: "RAILWAY_RELEASE_IDENTITY_MISSING",
    });
    assert.equal((cli.stdout + cli.stderr).includes("sentinel"), false);
    assert.equal((cli.stdout + cli.stderr).includes(A), false);
    let attempted = false;
    await assert.rejects(
      (async () => {
        await prepareReleaseIdentity({ outputPath, env: RAILWAY });
        attempted = true;
        await bundleMetadata(outputPath);
      })(),
      { code: "RAILWAY_RELEASE_IDENTITY_MISSING" }
    );
    assert.equal(attempted, false);
    assert.equal(hash(await readFile(outputPath)), hash(before));
  }
});

test("declaration-file contexts reject without native SHA but preserve native stamp priority", async t => {
  for (const fileName of [
    "releaseIdentity.d.ts",
    "releaseIdentity.d.mts",
    "releaseIdentity.d.cts",
  ]) {
    const outputPath = await fixture(t, value(B), fileName);
    assert.equal(
      readPreStampedReleaseIdentity(value(B), outputPath).status,
      "invalid"
    );
    await assert.rejects(prepareReleaseIdentity({ outputPath, env: RAILWAY }), {
      code: "RAILWAY_RELEASE_IDENTITY_MISSING",
    });
    assert.deepEqual(
      await prepareReleaseIdentity({
        outputPath,
        env: { ...RAILWAY, RAILWAY_GIT_COMMIT_SHA: A },
      }),
      { source: "railway-git" }
    );
    assert.equal(await readFile(outputPath, "utf8"), canonical);
    await verifyReleaseIdentity({ outputPath, releaseSha: A });
  }
});
