import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import {
  prepareReleaseIdentity,
  readPreStampedReleaseIdentity,
} from "./prepare-release-identity.mjs";
import { verifyReleaseIdentity } from "./stamp-release-identity.mjs";
import "./prepare-release-identity.ambient.test.mjs";

const SHA_A = "0123456789abcdef0123456789abcdef01234567";
const SHA_B = "abcdef0123456789abcdef0123456789abcdef01";
const actual = value => `export const RELEASE_SHA: string = "${value}";\n`;
const DEVELOPMENT = actual("development");
const RAILWAY = { RAILWAY_SERVICE_ID: "synthetic-ri01-service" };
const STAMPED_A =
  "// Generated by scripts/stamp-release-identity.mjs. Do not edit during deployment.\n" +
  actual(SHA_A);

async function fixture(t, source) {
  const prefix = join(tmpdir(), "boa-ri01-");
  const dir = await mkdtemp(prefix);
  t.after(async () => {
    assert.ok(dir.startsWith(prefix));
    await rm(dir, { recursive: true, force: true });
  });
  const outputPath = join(dir, "releaseIdentity.ts");
  if (source !== undefined) await writeFile(outputPath, source);
  return outputPath;
}

const negatives = [
  ["RI01-01 block comment", `/*\n${actual(SHA_A)}*/\n${DEVELOPMENT}`],
  ["RI01-02 line comment", `// ${actual(SHA_A)}${DEVELOPMENT}`],
  [
    "RI01-03 quoted export text",
    `const example = '${actual(SHA_A).trim()}';\n${DEVELOPMENT}`,
  ],
  [
    "RI01-04 template export text",
    `const example = \`\n${actual(SHA_A)}\`;\n${DEVELOPMENT}`,
  ],
  [
    "RI01-08 non-export declaration",
    `const RELEASE_SHA: string = "${SHA_A}";\n${DEVELOPMENT}`,
  ],
  [
    "RI01-09 duplicate exported declarations",
    `${actual(SHA_A)}${actual(SHA_B)}`,
    "RAILWAY_RELEASE_IDENTITY_AMBIGUOUS",
  ],
  [
    "RI01-11 dynamic initializer",
    `export const RELEASE_SHA: string = "${SHA_A}".trim();\n`,
  ],
];

for (const [
  name,
  source,
  code = "RAILWAY_RELEASE_IDENTITY_MISSING",
] of negatives) {
  test(`${name}: Railway rejects and preserves bytes`, async t => {
    const outputPath = await fixture(t, source);
    await assert.rejects(prepareReleaseIdentity({ env: RAILWAY, outputPath }), {
      code,
    });
    assert.deepEqual(await readFile(outputPath), Buffer.from(source));
  });
}

for (const [name, source] of [
  [
    "RI01-05 actual valid plus a different SHA in a block comment",
    `/*\n${actual(SHA_B)}*/\n${actual(SHA_A)}`,
  ],
  [
    "RI01-06 CRLF",
    `// existing stamp\r\n${actual(SHA_A).replaceAll("\n", "\r\n")}`,
  ],
  ["RI01-07 canonical", STAMPED_A],
]) {
  test(`${name}: preserves pre-stamp bytes`, async t => {
    const outputPath = await fixture(t, source);
    for (const env of [{}, RAILWAY]) {
      assert.deepEqual(await prepareReleaseIdentity({ env, outputPath }), {
        source: "pre-stamped",
      });
      assert.deepEqual(await readFile(outputPath), Buffer.from(source));
    }
  });
}

test("RI01-10 uppercase, short and long actual literals fail closed", async t => {
  for (const value of [SHA_A.toUpperCase(), SHA_A.slice(1), SHA_A + "a"]) {
    const source = actual(value);
    const outputPath = await fixture(t, source);
    await assert.rejects(prepareReleaseIdentity({ env: RAILWAY, outputPath }), {
      code: "RAILWAY_RELEASE_IDENTITY_MISSING",
    });
    assert.deepEqual(await readFile(outputPath), Buffer.from(source));
  }
});

test("RI01-12 native SHA stamps exactly before old hostile source is parsed", async t => {
  for (const source of [
    `/*\n${actual(SHA_B)}*/\n${DEVELOPMENT}`,
    actual(SHA_B) + actual(SHA_A),
    'export const RELEASE_SHA = "unterminated',
    'throw new Error("synthetic-ri01-source-sentinel");\n' + DEVELOPMENT,
  ]) {
    const outputPath = await fixture(t, source);
    assert.deepEqual(
      await prepareReleaseIdentity({
        env: { ...RAILWAY, RAILWAY_GIT_COMMIT_SHA: SHA_A },
        outputPath,
      }),
      { source: "railway-git" }
    );
    assert.deepEqual(await readFile(outputPath), Buffer.from(STAMPED_A));
    await verifyReleaseIdentity({ releaseSha: SHA_A, outputPath });
  }
});

test("RI01-13 local development remains a byte-preserving no-op", async t => {
  const outputPath = await fixture(t, DEVELOPMENT);
  assert.deepEqual(await prepareReleaseIdentity({ env: {}, outputPath }), {
    source: "development-noop",
  });
  assert.deepEqual(await readFile(outputPath), Buffer.from(DEVELOPMENT));
});

test("RI01-14 native SHA creates a missing file through the existing stamp helper", async t => {
  const outputPath = join(await fixture(t), "nested", "releaseIdentity.ts");
  assert.deepEqual(
    await prepareReleaseIdentity({
      env: { ...RAILWAY, RAILWAY_GIT_COMMIT_SHA: SHA_A },
      outputPath,
    }),
    { source: "railway-git" }
  );
  assert.deepEqual(await readFile(outputPath), Buffer.from(STAMPED_A));
  await verifyReleaseIdentity({ releaseSha: SHA_A, outputPath });
});

// Expected classifications and SHA values are fixture constants, not parser output.
const parserCases = [
  ["empty source", "", "missing"],
  ["block comment only", `/*\n${actual(SHA_A)}*/`, "missing"],
  ["line comment only", `// ${actual(SHA_A)}`, "missing"],
  ["quoted export only", `'${actual(SHA_A).trim()}';`, "missing"],
  ["template export only", `\`\n${actual(SHA_A)}\`;`, "missing"],
  ["non-export const", `const RELEASE_SHA = "${SHA_A}";`, "missing"],
  ["export let", `export let RELEASE_SHA = "${SHA_A}";`, "missing"],
  ["export var", `export var RELEASE_SHA = "${SHA_A}";`, "missing"],
  ["export using", `export using RELEASE_SHA = "${SHA_A}";`, "missing"],
  [
    "export await using",
    `export await using RELEASE_SHA = "${SHA_A}";`,
    "missing",
  ],
  ["other identifier", `export const OTHER_SHA = "${SHA_A}";`, "missing"],
  [
    "object property",
    `export const stamp = { RELEASE_SHA: "${SHA_A}" };`,
    "missing",
  ],
  [
    "nested namespace",
    `export namespace stamp { ${actual(SHA_A)} }`,
    "missing",
  ],
  ["nested block", `{ ${actual(SHA_A)} }`, "missing"],
  ["nested function", `function stamp() { ${actual(SHA_A)} }`, "missing"],
  [
    "destructuring",
    `export const { RELEASE_SHA } = { RELEASE_SHA: "${SHA_A}" };`,
    "missing",
  ],
  [
    "export list",
    `const RELEASE_SHA = "${SHA_A}"; export { RELEASE_SHA };`,
    "missing",
  ],
  ["actual development", DEVELOPMENT, "invalid"],
  ["no initializer", "export declare const RELEASE_SHA: string;", "invalid"],
  ["dynamic call", `export const RELEASE_SHA = String("${SHA_A}");`, "invalid"],
  ["concatenation", `export const RELEASE_SHA = "${SHA_A}" + "";`, "invalid"],
  [
    "parenthesized literal",
    `export const RELEASE_SHA = ("${SHA_A}");`,
    "invalid",
  ],
  [
    "type assertion",
    `export const RELEASE_SHA = "${SHA_A}" as string;`,
    "invalid",
  ],
  [
    "template initializer",
    `export const RELEASE_SHA = \`${SHA_A}\`;`,
    "invalid",
  ],
  ["uppercase SHA", actual(SHA_A.toUpperCase()), "invalid"],
  ["39 chars", actual(SHA_A.slice(1)), "invalid"],
  ["41 chars", actual(SHA_A + "a"), "invalid"],
  ["valid prefix plus suffix", actual(SHA_A + "-extra"), "invalid"],
  ["whitespace literal", actual(" " + SHA_A + " "), "invalid"],
  [
    "zero-width character",
    actual(SHA_A.slice(0, 20) + "\u200b" + SHA_A.slice(20)),
    "invalid",
  ],
  ["Unicode lookalike", actual("\uff10" + SHA_A.slice(1)), "invalid"],
  ["escaped Unicode SHA", actual("\\u0030" + SHA_A.slice(1)), "invalid"],
  ["escaped hex SHA", actual("\\x30" + SHA_A.slice(1)), "invalid"],
  [
    "escaped identifier",
    `export const RELEASE_\\u0053HA = "${SHA_A}";`,
    "invalid",
  ],
  [
    "malformed declaration",
    'export const RELEASE_SHA = "unterminated',
    "invalid",
  ],
  [
    "valid declaration plus parse error",
    actual(SHA_A) + "/* unterminated",
    "invalid",
  ],
  [
    "malformed unrelated statement",
    actual(SHA_A) + "const other = ;",
    "invalid",
  ],
  ["two valid exports", actual(SHA_A) + actual(SHA_B), "ambiguous"],
  ["development and valid exports", DEVELOPMENT + actual(SHA_A), "ambiguous"],
  ["same value twice", actual(SHA_A) + actual(SHA_A), "ambiguous"],
  [
    "same declaration list",
    `export const RELEASE_SHA = "${SHA_A}", RELEASE_SHA = "${SHA_B}";`,
    "ambiguous",
  ],
  [
    "escaped duplicate identifier",
    actual(SHA_A) + `export const RELEASE_\\u0053HA = "${SHA_B}";`,
    "ambiguous",
  ],
];

for (const [name, source, status] of parserCases) {
  test(`parser rejects ${name}`, () => {
    assert.deepEqual(readPreStampedReleaseIdentity(source), { status });
  });
}

for (const [name, source] of [
  ["canonical", STAMPED_A],
  [
    "single quotes and no type annotation",
    `export const RELEASE_SHA = '${SHA_A}';`,
  ],
  ["unrelated declarator", `export const OTHER = 1, RELEASE_SHA = "${SHA_A}";`],
  ["different comment SHA", `/*\n${actual(SHA_B)}*/\n${actual(SHA_A)}`],
  [
    "nested export with a different SHA",
    actual(SHA_A) + `namespace example { ${actual(SHA_B)} }`,
  ],
  [
    "source never executed",
    'throw new Error("synthetic-ri01-source-sentinel");\n' + actual(SHA_A),
  ],
]) {
  test(`parser accepts only the actual top-level literal: ${name}`, () => {
    assert.deepEqual(readPreStampedReleaseIdentity(source), {
      status: "valid",
      releaseSha: SHA_A,
    });
  });
}

test("all rejected parser fixtures fail closed on Railway and remain local no-ops", async t => {
  for (const [name, source, status] of parserCases) {
    const outputPath = await fixture(t, source);
    await assert.rejects(
      prepareReleaseIdentity({ env: RAILWAY, outputPath }),
      {
        code:
          status === "ambiguous"
            ? "RAILWAY_RELEASE_IDENTITY_AMBIGUOUS"
            : "RAILWAY_RELEASE_IDENTITY_MISSING",
      },
      name
    );
    assert.deepEqual(await readFile(outputPath), Buffer.from(source));
    assert.deepEqual(await prepareReleaseIdentity({ env: {}, outputPath }), {
      source: "development-noop",
    });
    assert.deepEqual(await readFile(outputPath), Buffer.from(source));
  }
});

test("CLI rejects adversarial pre-stamps with fixed codes and no source or env disclosure", async t => {
  for (const [source, code] of [
    [
      `/*\n${actual(SHA_A)}*/\n${DEVELOPMENT}`,
      "RAILWAY_RELEASE_IDENTITY_MISSING",
    ],
    [
      `const example = \`\n${actual(SHA_A)}\`;\n${DEVELOPMENT}`,
      "RAILWAY_RELEASE_IDENTITY_MISSING",
    ],
    [actual(SHA_A) + actual(SHA_B), "RAILWAY_RELEASE_IDENTITY_AMBIGUOUS"],
    [actual(SHA_A) + "/* unterminated", "RAILWAY_RELEASE_IDENTITY_MISSING"],
    [actual("\\u0030" + SHA_A.slice(1)), "RAILWAY_RELEASE_IDENTITY_MISSING"],
  ]) {
    const input = "// synthetic-ri01-source-sentinel\n" + source;
    const outputPath = await fixture(t, input);
    const cli = spawnSync(
      process.execPath,
      [
        fileURLToPath(
          new URL("./prepare-release-identity.mjs", import.meta.url)
        ),
        "--output",
        outputPath,
      ],
      {
        env: { RAILWAY_SERVICE_ID: "synthetic-ri01-env-sentinel" },
        encoding: "utf8",
      }
    );
    assert.equal(cli.status, 1);
    assert.equal(cli.stdout, "");
    assert.deepEqual(JSON.parse(cli.stderr), { ok: false, code });
    for (const forbidden of [
      SHA_A,
      SHA_B,
      "synthetic-ri01-source-sentinel",
      "synthetic-ri01-env-sentinel",
    ]) {
      assert.equal((cli.stdout + cli.stderr).includes(forbidden), false);
    }
    assert.deepEqual(await readFile(outputPath), Buffer.from(input));
  }
});
